# Generated by Django 2.2.16 on 2022-03-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220319_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default={'ZNao'}, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default={'WbIDXg'}, editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_users',
            field=models.TextField(blank=True),
        ),
    ]
