# Generated by Django 2.2.16 on 2022-03-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220319_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confermed',
            new_name='confirmed',
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default={'4def'}, editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default={'7Faead'}, editable=False, max_length=6),
        ),
    ]
