# Generated by Django 2.2.16 on 2022-03-21 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220320_0018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['phone_number'], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
        migrations.AddField(
            model_name='user',
            name='invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='6d2B', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='1Cae08', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(11, 'phone number must contain at least 11 characters')]),
        ),
    ]
