# Generated by Django 2.2.16 on 2022-03-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20220321_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='237d', editable=False, max_length=4),
        ),
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(default='DA9d19', editable=False, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='invited_users',
            field=models.TextField(blank=True, default='пока никого'),
        ),
    ]
