# Generated by Django 2.2.16 on 2022-03-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20220321_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invited_users',
            field=models.TextField(default='пока никого'),
        ),
    ]
